// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6_0FHb2wBAOyNj9NfDWAX6YLUdqz0FGI',
    appId: '1:498232253596:web:b1f90dd9041ec3d8f06159',
    messagingSenderId: '498232253596',
    projectId: 'awashz-e0c1c',
    authDomain: 'awashz-e0c1c.firebaseapp.com',
    storageBucket: 'awashz-e0c1c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDboB7Bfs-grDt-QF394nQGZkLqfCLu9LI',
    appId: '1:498232253596:android:0b82dde07742dd75f06159',
    messagingSenderId: '498232253596',
    projectId: 'awashz-e0c1c',
    storageBucket: 'awashz-e0c1c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCflYtTKBBlzaldfKhmkseAx-8fCr-R0Vc',
    appId: '1:498232253596:ios:9717dbfe27315886f06159',
    messagingSenderId: '498232253596',
    projectId: 'awashz-e0c1c',
    storageBucket: 'awashz-e0c1c.firebasestorage.app',
    iosBundleId: 'com.example.carWash',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCflYtTKBBlzaldfKhmkseAx-8fCr-R0Vc',
    appId: '1:498232253596:ios:9717dbfe27315886f06159',
    messagingSenderId: '498232253596',
    projectId: 'awashz-e0c1c',
    storageBucket: 'awashz-e0c1c.firebasestorage.app',
    iosBundleId: 'com.example.carWash',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6_0FHb2wBAOyNj9NfDWAX6YLUdqz0FGI',
    appId: '1:498232253596:web:e65f023aea3afb4ff06159',
    messagingSenderId: '498232253596',
    projectId: 'awashz-e0c1c',
    authDomain: 'awashz-e0c1c.firebaseapp.com',
    storageBucket: 'awashz-e0c1c.firebasestorage.app',
  );
}
